apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    chart: chart1-helm
    repoURL: https://gboie.github.io/chart1/
    helm:
      releaseName: chart1
  destination: 
    server: https://kubernetes.default.svc
    namespace: node-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true